language: node_js

services:
  - mongodb
  - docker

before_install:
  - ./run_docker.sh

before_script:
  - cp test/express/config.example.json test/express/config.json
after_script: npm run coverage

node_js:
  - '10'
  - '9'
  - '8'
  - '7'
  - '6'

cache:
  directories:
    - "node_modules"
