name: CI
on: 
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
      kafka:
        image: yunnysunny/kafka
        ports:
          - 9092:9092
        # options: --env KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    strategy:
      matrix:
       include:
        - node-version: 14.x
          pnpm-version: 7
        - node-version: 16.x
          pnpm-version: 8
    steps:
      - uses: actions/checkout@v2

      - name: Install Node - ${{ matrix.node-version }}
        uses: actions/setup-node@v2        
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: ${{ matrix.pnpm-version }}
          run_install: false
      - name: Create Config
        run: cp test/express/config.example.json test/express/config.json
      - name: Install Dependencies
        run: |
          if [ "${{ matrix.node-version }}" = "14.x" ]; then
            pnpm install --no-frozen-lockfile
          else
            pnpm install
          fi
      - name: Test On Node ${{ matrix.node-version }}

        run: |
          npm run test
      - name: Coverage on Node ${{ matrix.node-version }}
        run: npm run coverage
